### ISSUE TITLE
Wrong Video playing after private checklist toggle

### ISSUE THREAD

**Issue by martinvivek** [yedidiaklein/moodle-local_video_directory#10]
i was waiting for long time like this plugin, Thank you for this plugin and Sorry to create more issues, 
In the datatable i clicked the check box in private column refreshed and again checked it. now play button on the action column in any row, which video against you toggled the checkbox that video only playing.
and the player alignment should be little bit up. the controls are hidden

![image](https://cloud.githubusercontent.com/assets/7712010/25281667/a74de860-26cb-11e7-83fb-96674559d4ce.png)

**Comment by yedidiaklein** [comment]
First of all, I really appreciate your issues - that help us making a better and stable plugin.
The idea of private is to disallow access to these video to other video contributor... 
I see your issue... checking...

**Comment by yedidiaklein** [comment]
bug is fixed, please pull, purge all cache and it'll work.
