### ISSUE TITLE
Moodle coding style violations

### ISSUE THREAD

**Issue by damyon** [yedidiaklein/moodle-local_video_directory#11]
This issue was raised during a plugin review.

There are still thousands of coding style violations - please install the https://github.com/moodlehq/moodle-local_codechecker and check this yourself.
[warnings.txt](https://github.com/yedidiaklein/moodle-local_video_directory/files/1123454/warnings.txt)

**Comment by yedidiaklein** [comment]
fixed all warnings and errors of code checker
