### ISSUE TITLE
Debugging notices and errors in the UI

### ISSUE THREAD

**Issue by damyon** [yedidiaklein/moodle-local_video_directory#12]
This issue was raised during a plugin review.

There are warning messages and bugs in the UI. Examples:
** (Notice: Trying to get property of non-object in /home/damyon/moodles/integration_master/moodle/local/video_directory/init.php on line 72)
** DataTables warning: table id=video_table - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1
** Notice: Undefined offset: 1 in /home/damyon/moodles/integration_master/moodle/local/video_directory/init.php on line 72
** Notice: Trying to get property of non-object in /home/damyon/moodles/integration_master/moodle/local/video_directory/init.php on line 72

**Comment by yedidiaklein** [comment]
This happened while session was ended and ajax tried to get data...
Now, ajax is "moodle ajax" (service.php).
So we could get "servicenotavailable" in such cases...
