### ISSUE TITLE
Multiple security problems with AJAX scripts

### ISSUE THREAD

**Issue by damyon** [yedidiaklein/moodle-local_video_directory#23]
This issue was raised during a plugin review.

Your ajax scripts are wide open security holes. (Example ajax_edit.php has no protection for XSS, no validation of params, only security checks are indirect in the init.php). Please don't use custom scripts for ajax - create proper webservices and expose them to ajax like this: https://docs.moodle.org/dev/AJAX. Please only use PARAM_RAW as a last resort and if you have to use it - you must validate your own parameters properly before adding them to the database.

**Comment by yedidiaklein** [comment]
moved to moodle AJAX
