### ISSUE TITLE
Cannot Upgrade the plugin

### ISSUE THREAD

**Issue by martinvivek** [yedidiaklein/moodle-local_video_directory#6]
Today morning i downloaded and updated then i got this error

Unknown error upgrading local_video_directory to version 2017040403, can not continue.
Debug info: 
Error code: upgradeerror
Stack trace:
line 340 of \lib\upgradelib.php: upgrade_exception thrown
line 566 of \lib\upgradelib.php: call to upgrade_plugin_savepoint()
line 1748 of \lib\upgradelib.php: call to upgrade_plugins()
line 693 of \admin\index.php: call to upgrade_noncore()

**Comment by yedidiaklein** [comment]
there were missing return in the upgrade function... fixed (Thanks)
