### ISSUE TITLE
Video not working in Edit video link

### ISSUE THREAD

**Issue by martinvivek** [yedidiaklein/moodle-local_video_directory#9]
when i click the link moodleaddress/local/video_directory/edit.php?video_id=3
the video is not working, it is due to link used for the video is from streaming url/filename.mp4 not from play.php?video_id=id so it is not working.

and the courses in the edit page for what i dont know? may after documentation i may get

![image](https://cloud.githubusercontent.com/assets/7712010/25281091/dfd856c2-26c9-11e7-87cc-dbaff10346df.png)

**Comment by yedidiaklein** [comment]
Fixed to use play.php video on edit. also removed courses list, it's for future feature of a block that will show  course videos.
